# subscribe to added users
subscription UsersAdded {
  usersAdded {
    id
    name
    timestamp
  }
}

# Insert a new user and Publish
mutation InsertUsersAndPublish($name: String!) {
  insert_users(objects: { name: $name, rocket: "codegen" }) {
    affected_rows
    returning {
      name
      rocket
    }
  }
}
