query GetLaunches {
  launches {
    mission_id
    mission_name
  }
}

query GetLaunchesWithArgs($limit: Int) {
  launches(limit: $limit) {
    mission_id
    mission_name
  }
}

mutation UpdateUser($user: users_set_input, $where: users_bool_exp!) {
  update_users(_set: $user, where: $where) {
    affected_rows
    returning {
      id
      name
    }
  }
}

subscription NewUser {
  users {
    id
    name
    rocket
  }
}
